### ISSUE TITLE
(Suggestion) Masonry for cards

### ISSUE THREAD

**Issue by dragonfire1119** [bootcards/bootcards#29]
# Idea

Make the cards where they sit along side each other like google+ did.

**Comment by kamushadenes** [comment]
Mark,

I'm reopening this question because I can't make it work with dynamic cards (e.g. cards that are added or removed dynamically).

Checkout http://www.wookmark.com/jquery-plugin or http://masonry.desandro.com/.

Pinterest site is also a good source to check what I'm talking about.

How could we make this work?

Thanks for your attention.
