### ISSUE TITLE
Bower installation misses .css files

### ISSUE THREAD

**Issue by jshain** [bootcards/bootcards#39]
When installing bootcards via bower, the css files are not installed. This is probably due to the fact that bower.json refers to non-existing file "dist/css/bootcards.css".

**Comment by markleusink** [comment]
The reference in the 'main' section in the bower.json file was incorrect and I've updated that. But... that's not used when doing a bower install (see http://stackoverflow.com/questions/20391742/what-is-the-main-property-when-doing-bower-init). 

If you do a `bower install bootcards` of the latest release (v1.1.0) you'll get all the CSS files you need in the `dist` folder: the 'bootcards.css' file is already embedded into the files there.

The `dist` folder will contain 9 CSS files: 3 for desktop, Android and iOS. Typically you will only load 1 file (depending on the device that you're using or the look that you want). 

The files without the `-lite` extension have an embedded Bootstrap version (that's why they are about 7x the size of the other ones). I'd recommend to only load the -lite files: the files with an embedded Bootstrap version will be deprecated in the next release. If you do, don't forget to also load the Bootstrap CSS file.

**Comment by jshain** [comment]
You are right regarding bower install itself. But it turns out that the main property is used by [bower-installer tool](https://github.com/blittle/bower-installer), which imports only main files keeping the output folders clean.

Thank you for fixing the issue quickly!

**Comment by markleusink** [comment]
Thanks for letting me know. Hadn't heard of the tool and didn't know about it using the main property. I'll pay better attention to it in the future :-)
