### ISSUE TITLE
Need to be able to display more content in Navbar title

### ISSUE THREAD

**Issue by whitemx** [bootcards/bootcards#54]
Related to https://github.com/teamstudio/xcontrols-domino/issues/335

Basically on a phone we want to be able to have two lines of text. We had this working on an earlier version of Bootcards by simply adding a margin to the header, but that no longer works. Any ideas?

![image](https://cloud.githubusercontent.com/assets/856638/8993535/a6f200dc-36fd-11e5-88f1-ad96804ac9c3.png)

**Comment by markleusink** [comment]
I think this is something that @jackherbert needs to look into.

What HTML element received the bottom margin mentioned in the referenced issue? ( teamstudio/xcontrols-domino#335)

**Comment by whitemx** [comment]
We added it to the doc that contained the title text. But the header is very much separate from the body at this point so if we expand it, the body doesn't shift down.

**Comment by jackherbert** [comment]
I'm pretty sure the typical native behaviour for longer navbar titles would be to hide the overflow and add ellipsis when they get too long, rather than wrap them.

If we really need multiline titles, it's tricky to do with CSS responsively, because how do you know when the title breaks a line (i.e. at what screen width)? It might also vary between devices. I guess the line break could be hard-coded, but it might look daft on wider screens.

**Comment by whitemx** [comment]
I tend to agree, but what we're being asked for is to support adding a line break into the title. And then the header bar would expand to fit and the body would shift down so it's not hidden behind the header.

**Comment by jackherbert** [comment]
I can't seem to get Bootcards to compile properly, but if someone could add this it should fix it:

To `navbar-brand`:
```<span class="navbar-brand navbar-brand-multiline">```

To the CSS:

```.desktop .navbar-brand-multiline {
  margin-top: -12px !important;
}

.ios .navbar-brand-multiline {
  margin-top: 2px !important;
  line-height: 19px !important;
}

.android .navbar-brand-multiline {
  margin-top: -11px !important;
}
```

You may also want to play with the font size to get the effect you want, depending on the length of your titles. The navbar is fixed, so I'm afraid we can't easily make it expand in a way that the content underneath will react to. If was an absolute must, I guess we could add a body class in these situations to handle the taller nav and extra content offset/padding, but it'll look a bit strange.

As I said though, I don't think this is exactly optimal. A responsive, native-like solution would be truncating the strings if they are too long.

**Comment by sives** [comment]
Looking at the above screenshot, shouldn't we be moving the Add button down to the right of the search box (like we are doing in Isometrica).   You don't really need the title field "People" because the main title in the header bar is doing this job.  That leaves you with the space you need to deal with a two-line title and double height header bar

**Comment by sives** [comment]
Jack - if you can't get Bootcards to compile properly, you may need to raise an issue to that effect.  If other web designers can't get it to compile properly, then we've got a problem

**Comment by markleusink** [comment]
@jackherbert try running an `npm install` and `bower install` (once) before you compile using `grunt`

**Comment by jackherbert** [comment]
Thanks @markleusink 

I set it up locally according to the instructions you sent earlier in the year, but I'm getting a weird error when running `grunt watch`:

`Warning: EMFILE: Too many opened files.`

**Comment by markleusink** [comment]
Not seeing that, but this might help: https://www.npmjs.com/package/grunt-contrib-watch#how-do-i-fix-the-error-emfile-too-many-opened-files

**Comment by whitemx** [comment]
I manually added the change that @jackherbert mentioned above and it seems to work fine. Could we get that added to the main code?

In answer to @sives above, I think that what we're doing is a non standard use of Bootcards. Basically Rich is using a Form card in full screen mode so has custom buttons in the header bar, my screenshot above is just my test case to see what happens when I add a long chunk of text in the header.

**Comment by jackherbert** [comment]
Thanks @markleusink, but that hasn't helped unfortunately:

`Warning: EMFILE, too many open files`
...
`(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.`

Is there still something like a `grunt build` command for a manual build, rather than this `watch`? I tried `grunt build`, but it said task not found.

**Comment by jackherbert** [comment]
@whitemx I added that CSS to Bootcards

**Comment by whitemx** [comment]
Thanks, that's working fine for me now.

**Comment by whitemx** [comment]
Oh and by the way, not sure if it helps, but the brunt build worked fine on my machine as well.
