### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by jinco13** [bootcards/bootcards#71]
Hi, I just noticed your demo site(http://demo.bootcards.org) is down right now. I get the following error.

502 Bad Gateway
nginx/1.6.2 (Ubuntu)

**Comment by epugh** [comment]
This project really should have a “no longer maintained” message.   The curse of Github is that projects that were published and then are forgotten continue to lure innocent users in!

**Comment by jinco13** [comment]
Thanks for letting me know. I will create new issue on Github for "no longer maintained" feature.
https://github.com/isaacs/github

**Comment by markleusink** [comment]
@epugh You're absolutely right. Added the message to the readme.

BTW: demo app should be up again at http://demo.bootcards.org.

**Comment by epugh** [comment]
Thanks @markleusink 

I’m a somewhat lapsed committer at the Apache Software Foundation, and I’ve had a couple of projects that while emotionally near and dear to me, have hit their EOL, and moved to the Attic: http://attic.apache.org

It would be great if there was a way of telling Github that “this project is no longer actively maintained and shouldn’t be used” because technology has moved on!

I’m in the same boat of using Bootcards, and nervous about changing anything!

Eric
